# Generated by Django 5.1.4 on 2024-12-16 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailGroupDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='RemainderTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('before_duration', models.IntegerField()),
                ('remainder_frequency', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EmailGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=200)),
                ('groupdetails', models.ManyToManyField(related_name='email_groups', to='cg_remainders.emailgroupdetails')),
            ],
        ),
        migrations.AddField(
            model_name='emailgroupdetails',
            name='group_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_group_details', to='cg_remainders.emailgroups'),
        ),
        migrations.CreateModel(
            name='MailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('dateofsend', models.DateTimeField()),
                ('email_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cg_remainders.emailgroups')),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('state', models.CharField(choices=[('unsend', 'Unsend'), ('send', 'Send'), ('under_frequency', 'Under Frequency')], max_length=20)),
                ('mailgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cg_remainders.emailgroups')),
                ('remaindertype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cg_remainders.remaindertypes')),
            ],
        ),
    ]
