# Generated by Django 5.1.4 on 2024-12-19 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cg_remainders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailgroups',
            name='groupdetails',
        ),
        migrations.AlterField(
            model_name='emailgroupdetails',
            name='group_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupdetails', to='cg_remainders.emailgroups'),
        ),
    ]
